// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2RszbGIfQQwmQ9fgbESuK1qLN9ggEIE',
    appId: '1:734737565542:web:bc15ff2e7f6dc665f42aa7',
    messagingSenderId: '734737565542',
    projectId: 'beta-conquistando',
    authDomain: 'beta-conquistando.firebaseapp.com',
    storageBucket: 'beta-conquistando.appspot.com',
    measurementId: 'G-JR1HEF41WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN34VMXqa-Jt18rRvyXtaK4MwBxwxqTFM',
    appId: '1:734737565542:android:28860381b00b3c60f42aa7',
    messagingSenderId: '734737565542',
    projectId: 'beta-conquistando',
    storageBucket: 'beta-conquistando.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhIBBkUbl5RTSyi09rNgre1QuEpSCDhI',
    appId: '1:734737565542:ios:74e92498cbe58306f42aa7',
    messagingSenderId: '734737565542',
    projectId: 'beta-conquistando',
    storageBucket: 'beta-conquistando.appspot.com',
    iosClientId: '734737565542-gtkgd5nqse860is5c0e6oa50qndfvke1.apps.googleusercontent.com',
    iosBundleId: 'com.example.betaConquistando',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhIBBkUbl5RTSyi09rNgre1QuEpSCDhI',
    appId: '1:734737565542:ios:74e92498cbe58306f42aa7',
    messagingSenderId: '734737565542',
    projectId: 'beta-conquistando',
    storageBucket: 'beta-conquistando.appspot.com',
    iosClientId: '734737565542-gtkgd5nqse860is5c0e6oa50qndfvke1.apps.googleusercontent.com',
    iosBundleId: 'com.example.betaConquistando',
  );
}
